# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initiationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_initiationDialog(object):
    def setupUi(self, initiationDialog):
        initiationDialog.setObjectName("initiationDialog")
        initiationDialog.resize(399, 374)
        font = QtGui.QFont()
        font.setPointSize(8)
        initiationDialog.setFont(font)
        self.line = QtWidgets.QFrame(initiationDialog)
        self.line.setGeometry(QtCore.QRect(10, 40, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.importBtn = QtWidgets.QPushButton(initiationDialog)
        self.importBtn.setGeometry(QtCore.QRect(110, 10, 181, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.importBtn.setFont(font)
        self.importBtn.setObjectName("importBtn")
        self.nameLineEdit = QtWidgets.QLineEdit(initiationDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(180, 100, 191, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.yearLineEdit = QtWidgets.QLineEdit(initiationDialog)
        self.yearLineEdit.setGeometry(QtCore.QRect(210, 130, 31, 20))
        self.yearLineEdit.setObjectName("yearLineEdit")
        self.label = QtWidgets.QLabel(initiationDialog)
        self.label.setGeometry(QtCore.QRect(110, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.nameLabel = QtWidgets.QLabel(initiationDialog)
        self.nameLabel.setGeometry(QtCore.QRect(110, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLabel_2 = QtWidgets.QLabel(initiationDialog)
        self.nameLabel_2.setGeometry(QtCore.QRect(20, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.dawsonRadioButton = QtWidgets.QRadioButton(initiationDialog)
        self.dawsonRadioButton.setGeometry(QtCore.QRect(180, 160, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.dawsonRadioButton.setFont(font)
        self.dawsonRadioButton.setChecked(True)
        self.dawsonRadioButton.setObjectName("dawsonRadioButton")
        self.pearlandRadioButton = QtWidgets.QRadioButton(initiationDialog)
        self.pearlandRadioButton.setGeometry(QtCore.QRect(180, 180, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pearlandRadioButton.setFont(font)
        self.pearlandRadioButton.setObjectName("pearlandRadioButton")
        self.nameLabel_3 = QtWidgets.QLabel(initiationDialog)
        self.nameLabel_3.setGeometry(QtCore.QRect(10, 230, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.nameLabel_3.setFont(font)
        self.nameLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.pictureLineEdit = QtWidgets.QLineEdit(initiationDialog)
        self.pictureLineEdit.setGeometry(QtCore.QRect(80, 230, 251, 20))
        self.pictureLineEdit.setText("")
        self.pictureLineEdit.setObjectName("pictureLineEdit")
        self.browseButton = QtWidgets.QPushButton(initiationDialog)
        self.browseButton.setGeometry(QtCore.QRect(340, 230, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.browseButton.setFont(font)
        self.browseButton.setDefault(False)
        self.browseButton.setObjectName("browseButton")
        self.previewPic = QtWidgets.QLabel(initiationDialog)
        self.previewPic.setGeometry(QtCore.QRect(10, 260, 101, 101))
        self.previewPic.setText("")
        self.previewPic.setObjectName("previewPic")
        self.turnerRadioButton = QtWidgets.QRadioButton(initiationDialog)
        self.turnerRadioButton.setGeometry(QtCore.QRect(180, 200, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.turnerRadioButton.setFont(font)
        self.turnerRadioButton.setObjectName("turnerRadioButton")
        self.nameLabel_4 = QtWidgets.QLabel(initiationDialog)
        self.nameLabel_4.setGeometry(QtCore.QRect(100, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.nameLabel_4.setFont(font)
        self.nameLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel_4.setObjectName("nameLabel_4")
        self.notStudentCheckBox = QtWidgets.QCheckBox(initiationDialog)
        self.notStudentCheckBox.setGeometry(QtCore.QRect(40, 170, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.notStudentCheckBox.setFont(font)
        self.notStudentCheckBox.setObjectName("notStudentCheckBox")
        self.addPersonButton = QtWidgets.QPushButton(initiationDialog)
        self.addPersonButton.setGeometry(QtCore.QRect(130, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.addPersonButton.setFont(font)
        self.addPersonButton.setObjectName("addPersonButton")
        self.statusLabel = QtWidgets.QLabel(initiationDialog)
        self.statusLabel.setGeometry(QtCore.QRect(130, 320, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.statusLabel.setFont(font)
        self.statusLabel.setText("")
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(initiationDialog)
        QtCore.QMetaObject.connectSlotsByName(initiationDialog)

    def retranslateUi(self, initiationDialog):
        _translate = QtCore.QCoreApplication.translate
        initiationDialog.setWindowTitle(_translate("initiationDialog", "Add Person"))
        self.importBtn.setText(_translate("initiationDialog", "Mass Import (*.csv)"))
        self.label.setText(_translate("initiationDialog", "Manual Add"))
        self.nameLabel.setText(_translate("initiationDialog", "Name"))
        self.nameLabel_2.setText(_translate("initiationDialog", "Graduation Year   20"))
        self.dawsonRadioButton.setText(_translate("initiationDialog", "Dawson"))
        self.pearlandRadioButton.setText(_translate("initiationDialog", "Pearland"))
        self.nameLabel_3.setText(_translate("initiationDialog", "Picture"))
        self.browseButton.setText(_translate("initiationDialog", "Browse"))
        self.turnerRadioButton.setText(_translate("initiationDialog", "Turner"))
        self.nameLabel_4.setText(_translate("initiationDialog", "School"))
        self.notStudentCheckBox.setText(_translate("initiationDialog", "Not A Student"))
        self.addPersonButton.setText(_translate("initiationDialog", "Add Person"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    initiationDialog = QtWidgets.QDialog()
    ui = Ui_initiationDialog()
    ui.setupUi(initiationDialog)
    initiationDialog.show()
    sys.exit(app.exec_())

